# Generated by Django 3.2.4 on 2021-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('camera_description', models.CharField(max_length=100)),
                ('last_image_link', models.CharField(max_length=200)),
            ],
        ),
    ]
