# Generated by Django 3.2.4 on 2021-06-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0002_auto_20210621_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('detected_at', models.DateField()),
                ('classified_as', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='seconds_length',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trap',
            name='door_state',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='VideoDetail',
        ),
        migrations.AddField(
            model_name='alert',
            name='trap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vigilancia.trap'),
        ),
    ]
