# Generated by Django 3.2.4 on 2021-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0003_auto_20210625_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='detected_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trap',
            name='last_detected_movement_date',
            field=models.DateTimeField(),
        ),
    ]
